name: linux-build

on:
  push:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: recursive 
      
    - name: Install packages
      shell: bash
      run: ./install_ubuntu_packages.sh
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ 

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    
    - name: Upload files (Release) 
      uses: actions/upload-artifact@v3
      with:
        name: dab_radio_ubuntu_x64
        path: ${{github.workspace}}/build
